function hamsAudit(action,entityType,entityID,details){const a=JSON.parse(localStorage.getItem("HAMS_AuditLog")||"[]");a.unshift({auditID:"AUD-"+Date.now(),timestamp:new Date().toISOString(),user:localStorage.getItem("Employee")||"Unknown",employeeID:localStorage.getItem("EmployeeID")||"",role:localStorage.getItem("Role")||"",action,entityType,entityID,details:details||""});localStorage.setItem("HAMS_AuditLog",JSON.stringify(a));}
const dept=localStorage.getItem("CurrentDepartment");
const employee=localStorage.getItem("Employee")||"Unknown";
const currentDept=getDepartment(dept);
const params=new URLSearchParams(location.search),isGlobalScope=params.get("scope")==="all",filterParam=params.get("filter");
const INSPECTION_INTERVAL_DAYS=90,DUE_SOON_WINDOW_DAYS=14;
let selectedAssetID=null,selectedAssignmentAssetID=null;
function getInspections(){return JSON.parse(localStorage.getItem("Inspections"))||[]}
function saveInspections(x){localStorage.setItem("Inspections",JSON.stringify(x))}
function getAssignments(){return JSON.parse(localStorage.getItem("InspectionAssignments"))||[]}
function saveAssignments(x){localStorage.setItem("InspectionAssignments",JSON.stringify(x))}
function safe(v){return String(v??"—").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function daysBetween(a,b){return Math.floor((b-a)/86400000)}
function lastInspectionFor(id,ins){return ins.filter(x=>x.assetID===id).sort((a,b)=>new Date(b.date)-new Date(a.date))[0]||null}
function activeAssignmentFor(id,as){return as.filter(x=>x.assetID===id&&x.status==="Pending").sort((a,b)=>new Date(b.assignedDate)-new Date(a.assignedDate))[0]||null}
function latestAssignmentFor(id,as){return as.filter(x=>x.assetID===id).sort((a,b)=>new Date(b.assignedDate)-new Date(a.assignedDate))[0]||null}
function computeStatus(last){if(!last)return{label:"Never Inspected",badgeClass:"badge-condemned",daysSince:null};const d=daysBetween(new Date(last.date),new Date());if(last.condition==="Fail")return{label:"Fail",badgeClass:"badge-condemned",daysSince:d};if(last.condition==="Needs Attention")return{label:"Needs Attention",badgeClass:"badge-repair",daysSince:d};if(last.condition==="Asset Not Found")return{label:"Asset Not Found",badgeClass:"badge-condemned",daysSince:d};if(d>90)return{label:"Overdue",badgeClass:"badge-condemned",daysSince:d};if(d>76)return{label:"Due Soon",badgeClass:"badge-repair",daysSince:d};return{label:"OK",badgeClass:"badge-working",daysSince:d}}
function loadInspections(){
 const assets=JSON.parse(localStorage.getItem("Assets"))||[],ins=getInspections(),as=getAssignments();
 let list=assets.filter(a=>(isGlobalScope||a.departmentKey===dept||a.workDepartment===currentDept.code)&&a.verified===true);
 const df=document.getElementById("filterDept"),dv=df?df.value:""; if(dv)list=list.filter(a=>a.departmentKey===dv);
 const b=document.getElementById("block").value,s=document.getElementById("section").value,l=document.getElementById("location").value,sl=document.getElementById("subLocation").value;
 list=list.filter(a=>(!b||a.block===b)&&(!s||a.section===s)&&(!l||a.location===l)&&(!sl||a.subLocation===sl));
 if(filterParam==="inspected")list=list.filter(a=>ins.some(i=>i.assetID===a.assetID));
 const table=document.getElementById("inspectionTable");table.innerHTML="";let c={never:0,overdue:0,dueSoon:0,ok:0,fail:0,needs:0,awaiting:0,pending:0};
 if(!list.length){table.innerHTML=`<tr class="empty-row"><td colspan="${isGlobalScope?8:7}">No assets match the selected filters.</td></tr>`}
 list.forEach(a=>{
  const last=lastInspectionFor(a.assetID,ins),st=computeStatus(last),active=activeAssignmentFor(a.assetID,as),latest=latestAssignmentFor(a.assetID,as);
  if(st.label==="Never Inspected")c.never++;else if(["Fail","Asset Not Found"].includes(st.label))c.fail++;else if(st.label==="Needs Attention")c.needs++;else if(st.label==="Overdue")c.overdue++;else if(st.label==="Due Soon")c.dueSoon++;else c.ok++;
  if(active)c.pending++;else if(!latest)c.awaiting++;
  const deptCell=isGlobalScope?`<td>${safe(getDepartment(a.departmentKey).name)}</td>`:"";
  let assign=active?`<span class="assignment-badge assignment-pending">🔵 Assigned</span><div style="font-size:11px;color:var(--color-muted);margin-top:4px;">${safe(getDepartment(active.departmentKey).name)} · Due ${active.dueDate?safe(new Date(active.dueDate+"T00:00:00").toLocaleDateString()):"—"}</div>`:latest&&latest.status==="Completed"?`<span class="assignment-badge assignment-complete">🟢 Completed</span>`:`<span class="assignment-badge assignment-awaiting">🟡 Awaiting Assignment</span>`;
  let actions=`<div style="display:flex;gap:7px;flex-wrap:wrap;align-items:center"><button class="btn-icon" title="View complete asset details" onclick="openDetailModal('${safe(a.assetID)}')">👁</button><button class="btn-icon" title="Asset 360°" onclick="location.href='asset_360.html?assetID=${encodeURIComponent(a.assetID)}'">◉</button><button class="btn-icon" title="Fault Tracking" onclick="location.href='fault_tracking.html?assetID=${encodeURIComponent(a.assetID)}'">⚠️</button><button class="btn-icon" title="Edit asset" onclick="editAsset('${safe(a.assetID)}')">✏️</button>`;
  if(isGlobalScope&&!active)actions+=`<button class="btn btn-secondary" style="padding:8px 12px;font-size:12px" onclick="openAssignmentModal('${safe(a.assetID)}')">📋 Assign for Inspection</button>`;
  else if(active&&active.departmentKey===dept)actions+=`<button class="btn btn-primary" style="padding:8px 12px;font-size:12px" onclick="openInspectionModal('${safe(a.assetID)}')">🔍 Inspect</button>`;
  if(last)actions+=`<button class="btn btn-secondary" style="padding:8px 12px;font-size:12px" title="Reverse Asset Inspection" onclick="openReverseInspection('${safe(a.assetID)}')">↩️ Reverse Inspection</button>`;
  actions+=`</div>`;
  table.innerHTML+=`<tr><td>${safe(a.assetID)}</td><td>${safe(a.assetName)}</td>${deptCell}<td>${last?new Date(last.date).toLocaleDateString():"—"}</td><td>${st.daysSince===null?"—":st.daysSince+" day(s) ago"}</td><td><span class="badge ${st.badgeClass}">${safe(st.label)}</span></td><td>${assign}</td><td>${actions}</td></tr>`;
 });
 ["statNever","statFail","statNeedsAttention","statOverdue","statDueSoon","statOK"].forEach((id,i)=>document.getElementById(id).textContent=[c.never,c.fail,c.needs,c.overdue,c.dueSoon,c.ok][i]);
 document.getElementById("statAwaiting").textContent=c.awaiting;document.getElementById("statPending").textContent=c.pending;
}
function openDetailModal(id){
 const assets=JSON.parse(localStorage.getItem("Assets"))||[],ins=getInspections(),as=getAssignments(),a=assets.find(x=>x.assetID===id);if(!a)return;
 const fields=[["Asset ID",a.assetID],["Asset Name",a.assetName],["Manufacturer",a.manufacturer],["Model",a.model],["Serial Number",a.serial],["Category",a.category],["Sub Category",a.subcategory],["Division",a.division],["Department",a.department||getDepartment(a.departmentKey).name],["Work Department",a.workDepartment],["Block",a.block],["Section",a.section],["Location",a.location],["Sub Location",a.subLocation],["Asset Type",a.assetType],["Custodian",a.custodian],["Used By",a.usedBy],["Status",a.status],["Verification",a.verified?"✅ Verified":"❌ Unverified"],["Verified By",a.verifiedBy],["Verified On",a.verifiedDate?new Date(a.verifiedDate).toLocaleString():"—"]];
 document.getElementById("detailModalTitle").textContent=a.assetName+" ("+a.assetID+")";
 document.getElementById("detailFields").innerHTML=`<div class="detail-grid">${fields.map(f=>`<div class="detail-field"><span>${safe(f[0])}</span><span>${safe(f[1]||"—")}</span></div>`).join("")}</div>`;
 const ah=as.filter(x=>x.assetID===id).sort((x,y)=>new Date(y.assignedDate)-new Date(x.assignedDate));const ih=ins.filter(x=>x.assetID===id).sort((x,y)=>new Date(y.date)-new Date(x.date));
 let out=`<h5 style="margin:16px 0 8px">Inspection Assignments</h5>`+(ah.length?ah.map(x=>`<div style="padding:10px 0;border-bottom:1px solid var(--color-line)"><b>${safe(getDepartment(x.departmentKey).name)} — ${safe(x.status)}</b><div style="font-size:12.5px;color:var(--color-muted)">Assigned by ${safe(x.assignedBy)} · ${new Date(x.assignedDate).toLocaleString()}${x.dueDate?" · Due "+new Date(x.dueDate+"T00:00:00").toLocaleDateString():""}</div>${x.notes?`<div>${safe(x.notes)}</div>`:""}</div>`).join(""):"<p style='color:var(--color-muted);font-size:13px'>No assignment history yet.</p>");
 out+=`<h5 style="margin:16px 0 8px">Inspection History</h5>`+(ih.length?ih.map(x=>`<div style="padding:10px 0;border-bottom:1px solid var(--color-line)"><b>${new Date(x.date).toLocaleString()} — ${safe(x.condition)}</b><div style="font-size:12.5px;color:var(--color-muted)">By ${safe(x.inspectedBy)}${x.notes?" · "+safe(x.notes):""}</div></div>`).join(""):"<p style='color:var(--color-muted);font-size:13px'>No inspection history yet.</p>");
 document.getElementById("detailHistory").innerHTML=out;document.getElementById("detailModal").classList.add("open");
}
function openReverseInspection(id){location.href="reverse_asset_inspection.html?assetID="+encodeURIComponent(id)}
function closeDetailModal(){document.getElementById("detailModal").classList.remove("open")}
function editAsset(id){const a=JSON.parse(localStorage.getItem("Assets"))||[],i=a.findIndex(x=>x.assetID===id);if(i<0)return;localStorage.setItem("SelectedAsset",String(i));location.href="edit_asset.html"}
function openAssignmentModal(id){const a=(JSON.parse(localStorage.getItem("Assets"))||[]).find(x=>x.assetID===id);if(!a)return;selectedAssignmentAssetID=id;const d=getDepartment(a.departmentKey||dept);document.getElementById("assignmentAssetName").textContent=a.assetName+" ("+a.assetID+")";document.getElementById("assignmentDepartment").innerHTML=`<option value="${safe(d.key)}">${safe(d.name)} (${safe(d.code)})</option>`;const due=new Date();due.setDate(due.getDate()+7);document.getElementById("assignmentDueDate").value=due.toISOString().slice(0,10);document.getElementById("assignmentNotes").value="";document.getElementById("assignmentModal").classList.add("open")}
function closeAssignmentModal(){document.getElementById("assignmentModal").classList.remove("open");selectedAssignmentAssetID=null}
function saveInspectionAssignment(){if(!selectedAssignmentAssetID)return;const assets=JSON.parse(localStorage.getItem("Assets"))||[],a=assets.find(x=>x.assetID===selectedAssignmentAssetID);if(!a||!a.verified)return alert("Only verified assets can be assigned for inspection.");const as=getAssignments();if(activeAssignmentFor(selectedAssignmentAssetID,as))return alert("This asset is already assigned and waiting for inspection.");const d=document.getElementById("assignmentDepartment").value;as.push({assignmentID:"INSP-"+Date.now(),assetID:selectedAssignmentAssetID,departmentKey:d,assignedBy:employee,assignedDate:new Date().toISOString(),dueDate:document.getElementById("assignmentDueDate").value,notes:document.getElementById("assignmentNotes").value.trim(),status:"Pending"});saveAssignments(as);closeAssignmentModal();loadInspections();alert("Asset assigned to "+getDepartment(d).name+" for inspection.")}
function openInspectionModal(id){const as=getAssignments(),a=activeAssignmentFor(id,as);if(!a)return alert("This asset has not been assigned for inspection.");if(!isGlobalScope&&a.departmentKey!==dept)return alert("This inspection is assigned to "+getDepartment(a.departmentKey).name+".");const asset=(JSON.parse(localStorage.getItem("Assets"))||[]).find(x=>x.assetID===id);if(!asset)return;selectedAssetID=id;document.getElementById("modalAssetName").textContent=asset.assetName+" ("+asset.assetID+")";["checkPresent","checkLocation","checkIdentity","checkWorking"].forEach(id=>document.getElementById(id).value="Yes");["checkDamage","checkFault"].forEach(id=>document.getElementById(id).value="No");document.getElementById("inspectionCondition").value="Pass";document.getElementById("inspectionNotes").value="";document.getElementById("inspectionModal").classList.add("open")}
function closeInspectionModal(){document.getElementById("inspectionModal").classList.remove("open");selectedAssetID=null}
function saveInspectionEntry(){if(!selectedAssetID)return;const as=getAssignments(),idx=as.findIndex(x=>x.assetID===selectedAssetID&&x.status==="Pending");if(idx<0)return alert("No pending inspection assignment was found.");const now=new Date().toISOString(),ins=getInspections();ins.push({inspectionID:"INSPLOG-"+Date.now(),assetID:selectedAssetID,date:now,inspectedBy:employee,departmentKey:dept,assignmentID:as[idx].assignmentID,condition:document.getElementById("inspectionCondition").value,checks:{assetPresent:document.getElementById("checkPresent").value,correctLocation:document.getElementById("checkLocation").value,identificationCorrect:document.getElementById("checkIdentity").value,workingNormally:document.getElementById("checkWorking").value,physicalDamage:document.getElementById("checkDamage").value,faultFound:document.getElementById("checkFault").value},notes:document.getElementById("inspectionNotes").value.trim()});as[idx].status="Completed";as[idx].completedDate=now;as[idx].completedBy=employee;saveInspections(ins);saveAssignments(as);closeInspectionModal();loadInspections();alert("Inspection completed and recorded.")}
function populateDeptFilter(){const el=document.getElementById("filterDept");if(!el)return;getDepartments().forEach(d=>{const o=document.createElement("option");o.value=d.key;o.textContent=d.name;el.appendChild(o)})}
function clearFilters(){const d=document.getElementById("filterDept");if(d)d.value="";document.getElementById("block").value="";document.getElementById("section").innerHTML='<option value="">All Sections</option>';document.getElementById("location").innerHTML='<option value="">All Locations</option>';document.getElementById("subLocation").innerHTML='<option value="">All Sub Locations</option>';loadInspections()}
populateDeptFilter();["filterDept","block","section","location","subLocation"].forEach(id=>{const e=document.getElementById(id);if(e)e.addEventListener("change",loadInspections)});loadInspections();
